plt.subplot(3,1,1)
plt.bar(x,FINAL1)
plt.title("Promedio de Pasos con Politica "+ALG+"-Greedy")
plt.grid(True)
plt.ylim(0,120)

plt.subplot(3,1,2)
plt.bar(x,FINAL2)
plt.title("Promedio de Pasos con Politica "+ALG+"-Softmax")
plt.grid(True)
plt.ylim(0,120)

plt.subplot(3,1,3)
plt.bar(x,FINAL3)
plt.title("Promedio de Pasos con Politica "+ALG+"-Boltzmann")
plt.grid(True)
plt.ylim(0,120)

plt.tight_layout()
plt.show()
